# --- Basic options --- #

# Name of website
title: Cogitate

# Short description of your site
description: Exploring thoughts

# Your name to show in the footer
author: Felix Karg

# --- List of links in the navigation bar --- #

navbar-links:
  More:
    - Privacy Policy: "privacy_policy"
    - Favicon Attribution: "attribution"
  About Me: "aboutme"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
# avatar: "/assets/img/avatar-icon.png"

# By default, the image is cut into a circle. You can disable this behaviour by
# setting 'round-avatar: false'
# round-avatar: true

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image


# --- Footer options --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
# If you don't want to show a link to an RSS feed, set rss to "false".
social-network-links:
  rss: true
  email: "fkarg10@gmail.com"
  #   facebook: daattali
  github: fkarg
  #   twitter: yourname
#  reddit: yourname

#  linkedin: felix-karg-33973b178
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: yourname
#  instagram: yourname
#  youtube: user/yourname
#  spotify: yourname
#  telephone: +14159998888
#  steam: yourname
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  ORCID: your ORCID ID
#  google-scholar: your google scholar

# --- General options --- #

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "fkarg.github.io"

# Create a "tags" index page and make tags on each post clickable
link-tags: true

# Excerpt Word Length - Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50
excerpt_separator: "* TOC"


# The keywords to associate with your website, for SEO purposes
#keywords: "my,list,of,keywords"

# --- Colours / background image --- #

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

# For any extra customization, you can include additional CSS files in every page on your site
#site-css:
#  - "/assets/css/custom-styles.css"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
# gtag: "<!-- Global site tag (gtag.js) - Google Analytics -->
# <script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-139307239-1\"></script>
# <script>
#   window.dataLayer = window.dataLayer || [];
#   function gtag(){dataLayer.push(arguments);}
#   gtag('js', new Date());
# 
#   gtag('config', 'UA-139307239-1');
# </script>
# "
#
# Fill in your Google Analytics ID to track your website using GA
# google_analytics: "UA-139307239-1"

# Google Tag Manager ID
#gtm: ""


# adding the Matomo gtag:
# 
# gtag: "<!-- Matomo -->
# <script type=\"text/javascript\">
#   var _paq = window._paq || [];
#   /* tracker methods like \"setCustomDimension\" should be called before \"trackPageView\" */
#   _paq.push(['trackPageView']);
#   _paq.push(['enableLinkTracking']);
#   (function() {
#     var u=\"https://github.matomo.cloud/\";
#     _paq.push(['setTrackerUrl', u+'matomo.php']);
#     _paq.push(['setSiteId', '1']);
#     var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
#     g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
#   })();
# </script>
# <!-- End Matomo Code -->"

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
# matomo:
#   site_id: "1"
#   uri: "github.matomo.cloud/"
#   opt-out: true

# --- Comments --- #

# To use Utterances comments: (0) uncomment the following section, (1) fill in
# "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# (3) Install the Utterances app in your repository https://github.com/apps/utterances
# See more details about the parameters below at https://utteranc.es/
#utterances:
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  issue-term: title   # Mapping between blog posts and GitHub issues
#  theme: github-light # Utterances theme
#  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

# To use Staticman comments, first invite `staticmanlab` as a collaborator to your repository and
# accept the invitation by going to `https://staticman3.herokuapp.com/v3/connect/github/<username>/<repo-name>`.
# Then uncomment the following section and fill in "repository" and "branch".
# If you want to use reCaptcha for staticman (optional for spam protection), then fill
# in the "siteKey" and "secret" parameters below and also in `staticman.yml`.
# See more details at https://staticman.net/

# Staticman support
staticman:
  repository : fkarg/fkarg.github.io
  # GitHub username/repository eg. "daattali/beautiful-jekyll"
  branch     : master
      # eg. "master" If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
  endpoint   : https://staticmanat.herokuapp.com/v3/entry/github/
#   (optional) URL of your own deployment, with a trailing slash eg. https://<your-api>/v3/entry/github/ (will fallback to a public GitLab instance)
#   reCaptcha:
#     # reCaptcha for Staticman (OPTIONAL)
#     # If you use reCaptcha, you must also set these parameters in staticman.yml
#     siteKey  : "6LfqSJ8UAAAAAHcR84-QqKY2ZsbAzxx21YDRkgjq"
#         # Use your own site key, you need to apply for one on Google
#         #     secret   : "6LduRZ8UAAAAAPOsb1L_HFhrIXiIbtLuNpWJ44sy"
#         #     secret   : "6LfqSJ8UAAAAAENw93G5V3gP5ul5OUpkDbzM_DFo"
#     secret   : "BujKw292lJjh9VDsssNeQkYljZYrSeRZiMmU7IO27Wutz/zoRiaBq4u6hGeOome/y++BEFGhqSwU2GnB24lVuEz1gMIW97J/bOEeHneNlISB/r5PxrlMwe7v+C5v6SXjA9IRwdihNC5EPA0h6x2/raOWq05hxzmVZuGv/2TwOoTepSvJT8F5Iwp3s9Wb4mGamf9ALhz4DXmcDaLdqMIYj0jSyammkTCqjjsb2TOxpOxyvGdK7IpCOSNGT6wtLXqin/BJ8YZePJIBwJyb1/a/xGRAe1sC3/IbRsIiCPYnMInHv6Zy8Rt92mWnhU4L+UD/LtyJr8dLRBqhoUUL9ltP2g=="
        # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>


# --- Misc --- #

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""


# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Berlin"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM
  math_engine: mathjax

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      published: true
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: true # add word count on all blog posts
      tex: false  # deactivate tex-support globally. activate individually.
  -
    scope:
      path: "staged"
    values:
      layout: "post"
      readtime: true
      published: true
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
    # other stuff
  - drafts/
  - docs/
  - staged/*.py
  - staged/*.txt
    # nix-shell stuff
  - Gemfile-nix-shell
  - default.nix
  - gemset.nix
  - vendor
  - result

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189

# hide future posts
# future: false
